In [7]:
import pandas as pd
xrefs_file="../ontology/xref-all.tsv"
obsoletes_file="../ontology/obsoletes_ordo.tsv"
diff_assertions_file="../ontology/reports/report-all-properties.tsv"
df_xrefs=pd.read_csv(xrefs_file,sep="\t")
df_ordo=pd.read_csv(obsoletes_file,sep="\t")
df_ordo['deprecated']=True
df_ordo.head()

,?cls,?comment,?curie,deprecated
0,<http://www.orpha.net/ORDO/Orphanet_100039>,This class is deprecated. The preferred class ...,Orphanet:100039,True
1,<http://www.orpha.net/ORDO/Orphanet_100040>,use http://www.orpha.net/ORDO/Orphanet_90044 w...,Orphanet:100040,True
2,<http://www.orpha.net/ORDO/Orphanet_100041>,use http://www.orpha.net/ORDO/Orphanet_90044 w...,Orphanet:100041,True
3,<http://www.orpha.net/ORDO/Orphanet_100072>,use http://www.orpha.net/ORDO/Orphanet_97330 w...,Orphanet:100072,True
4,<http://www.orpha.net/ORDO/Orphanet_100932>,use http://www.orpha.net/ORDO/Orphanet_519349 ...,Orphanet:100932,True

In [15]:
df_xrefs[~df_xrefs['?deprecated'].isna()].head()

,?cls,?type,?xref,?prefix,?deprecated
35442,<http://purl.obolibrary.org/obo/MONDO_0020185>,MONDO:equivalentTo,Orphanet:98595,Orphanet,True
37258,<http://purl.obolibrary.org/obo/MONDO_0020186>,MONDO:equivalentTo,Orphanet:98596,Orphanet,True
38104,<http://purl.obolibrary.org/obo/MONDO_0018797>,MONDO:equivalentTo,Orphanet:477805,Orphanet,True
38256,<http://purl.obolibrary.org/obo/MONDO_0020190>,MONDO:equivalentTo,Orphanet:98600,Orphanet,True
38677,<http://purl.obolibrary.org/obo/MONDO_0020187>,MONDO:equivalentTo,Orphanet:98597,Orphanet,True

In [24]:
df_xrefs_ordo=df_xrefs[(df_xrefs['?prefix']=="Orphanet")]
df_xrefs_ordo = df_xrefs_ordo.merge(df_ordo[['?curie','deprecated']], left_on=['?xref'], right_on=['?curie'])
print(len(df_xrefs_ordo))
df_xrefs_ordo.head()

478

,?cls,?type,?xref,?prefix,?deprecated,?curie,deprecated
0,<http://purl.obolibrary.org/obo/MONDO_0010265>,MONDO:equivalentTo,Orphanet:79022,Orphanet,NaN,Orphanet:79022,True
1,<http://purl.obolibrary.org/obo/MONDO_0020172>,MONDO:equivalentTo,Orphanet:98581,Orphanet,NaN,Orphanet:98581,True
2,<http://purl.obolibrary.org/obo/MONDO_0000229>,MONDO:equivalentTo,Orphanet:101335,Orphanet,NaN,Orphanet:101335,True
3,<http://purl.obolibrary.org/obo/MONDO_0014129>,MONDO:equivalentTo,Orphanet:363543,Orphanet,NaN,Orphanet:363543,True
4,<http://purl.obolibrary.org/obo/MONDO_0020208>,MONDO:equivalentTo,Orphanet:98620,Orphanet,NaN,Orphanet:98620,True

In [25]:
df_xrefs_ordo.to_csv("../ontology/ordo_deprecated.tsv", sep="\t")

# SSSOM Files

In [7]:
import pandas as pd
from pathlib import Path
from argparse import ArgumentParser

curiemap = {
    'OMIM': 'http://omim.org/entry/',                    
    'OMIMPS': 'http://www.omim.org/phenotypicSeries/', 
    'ORPHA': 'http://www.orpha.net/ORDO/Orphanet_',
    'MONDO': 'http://purl.obolibrary.org/obo/MONDO_'
}

def get_dataframe(tsv):
    try:
        df = pd.read_csv(tsv,sep="\t", comment="#")
        df["source"]=Path(tsv).stem
        return df
    except pd.errors.EmptyDataError:
        print("WARNING! ", tsv, " is empty and has been skipped.")

sssom_tsv_path = "/Users/matentzn/ws/mondo/src/ontology/mappings/ordo-omim.sssom.tsv"
df = get_dataframe(sssom_tsv_path)

sssom_files = {}

for index, row in df.iterrows():
    object_id = row["object_id"]
    prefix = object_id.split(":")[0]
    if prefix not in sssom_files:
        sssom_files[prefix] = []
    sssom_files[prefix].append(row)

for prefix in sssom_files:
    if
    print(prefix)

print(df.head())

OMIM
UMLS
ICD-10
MedDRA
MeSH
SwissProt
Genatlas
Ensembl
HGNC
Reactome
IUPHAR
                               subject_id        predicate_id      object_id  \
0  http://www.orpha.net/ORDO/Orphanet_124  oboInOwl:hasDbXref    OMIM:612561
1  http://www.orpha.net/ORDO/Orphanet_124  oboInOwl:hasDbXref    OMIM:617409
2  http://www.orpha.net/ORDO/Orphanet_124  oboInOwl:hasDbXref  UMLS:C2931850
3  http://www.orpha.net/ORDO/Orphanet_124  oboInOwl:hasDbXref    OMIM:615909
4  http://www.orpha.net/ORDO/Orphanet_124  oboInOwl:hasDbXref    OMIM:300946

            source
0  ordo-omim.sssom
1  ordo-omim.sssom
2  ordo-omim.sssom
3  ordo-omim.sssom
4  ordo-omim.sssom

In [1]:
ps = "https://omim.org/phenotypicSeriesTitles/all?format=tsv"
mim2gene = "https://omim.org/static/omim/data/mim2gene.txt"
mimTitles = "https://data.omim.org/downloads/Wi95pIjsRfqt4ioi9rEJNQ/mimTitles.txt"
genemap2 = "https://data.omim.org/downloads/Wi95pIjsRfqt4ioi9rEJNQ/genemap2.txt"
morbidmap = "https://data.omim.org/downloads/Wi95pIjsRfqt4ioi9rEJNQ/morbidmap.txt"

In [4]:
import pandas as pd
df_ps = pd.read_csv(ps,sep="\t")

In [5]:
df_ps.head()

                                     <!DOCTYPE html>
0  <html xmlns="http://www.w3.org/1999/xhtml" lan...
1                                             <head>
2                           <title>Error 403</title>
3      <meta contentType-equiv="Content-Type" con...
4                                            </head>

In [1]:
import pandas as pd
diff_current_file="../ontology/reports/report-2020-06-30-release.tsv"
diff_compare_file="../ontology/reports/report-2019-06-29-release.tsv"
raw=pd.read_csv(diff_current_file,sep="\t")
raw=raw.fillna("None")
raw2=pd.read_csv(diff_compare_file,sep="\t")
raw2=raw2.fillna("None")
replace=dict()
replace['<http://purl.obolibrary.org/obo/IAO_']="IAO:"
replace['<http://purl.obolibrary.org/obo/mondo#']="mondo:"
replace['<http://purl.org/dc/elements/1.1/']="dce:"
replace['<http://purl.org/dc/terms/']="dc:"
replace['<http://www.geneontology.org/formats/oboInOwl#']="oio:"
replace['<http://www.w3.org/1999/02/22-rdf-syntax-ns#']="rdf:"
replace['<http://www.w3.org/2000/01/rdf-schema#']="rdfs:"
replace['<http://www.w3.org/2002/07/owl#']="owl:"
replace['<http://www.w3.org/2004/02/skos/core#']="skos:"
replace['>']=""
raw2

,?term,?property,?value,?p,?v
0,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.geneontology.org/formats/oboInOwl#...,GARD:0008595,<http://www.geneontology.org/formats/oboInOwl#...,Orphanet-shared
1,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.geneontology.org/formats/oboInOwl#...,GARD:0008595,<http://www.geneontology.org/formats/oboInOwl#...,OMIM-shared
2,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.geneontology.org/formats/oboInOwl#...,GARD:0008595,<http://www.geneontology.org/formats/oboInOwl#...,MONDO:equivalentTo
3,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.w3.org/2000/01/rdf-schema#subClassOf>,<http://purl.obolibrary.org/obo/MONDO_0016133>,<http://www.geneontology.org/formats/oboInOwl#...,Orphanet:96
4,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.w3.org/2002/07/owl#equivalentClass>,<http://purl.obolibrary.org/obo/OMIM_277460>,None,None
...,...,...,...,...,...
635874,<http://purl.obolibrary.org/obo/MONDO_0022921>,<http://www.geneontology.org/formats/oboInOwl#...,<http://purl.obolibrary.org/obo/mondo#gard_rare>,None,None
635875,<http://purl.obolibrary.org/obo/MONDO_0022921>,<http://www.geneontology.org/formats/oboInOwl#...,short stature microcephaly heart defect,<http://www.geneontology.org/formats/oboInOwl#...,GARD:0000233
635876,<http://purl.obolibrary.org/obo/MONDO_0022921>,<http://www.w3.org/2002/07/owl#deprecated>,true,None,None
635877,<http://purl.obolibrary.org/obo/MONDO_0700005>,<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>,<http://www.w3.org/2002/07/owl#Class>,None,None
635878,<http://purl.obolibrary.org/obo/MONDO_0700006>,<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>,<http://www.w3.org/2002/07/owl#Class>,None,None

In [2]:
df2=raw2[['?term','?property','?value','?p','?v']].drop_duplicates()
df2['?property'] = df2['?property'].replace(replace, regex=True)
df2['?p'] = df2['?p'].replace(replace, regex=True)

In [3]:
df1=raw[['?term','?property','?value','?p','?v']].drop_duplicates()
df1['?property'] = df1['?property'].replace(replace, regex=True)
df1['?p'] = df1['?p'].replace(replace, regex=True)

In [4]:
df=pd.concat([df1, df2, df2]).drop_duplicates(keep=False)
df.to_csv("check.tsv",sep="\t")

In [5]:
df[['?term','?property']].drop_duplicates().groupby(['?property']).agg(['count'])

                          ?term
                          count
?property
IAO:0000115                 225
IAO:0000231                   8
IAO:0100001                 103
mondo:excluded_subClassOf   154
mondo:excluded_synonym        1
oio:consider                  8
oio:created_by               35
oio:hasAlternativeId          3
oio:hasBroadSynonym          14
oio:hasDbXref               995
oio:hasExactSynonym         702
oio:hasNarrowSynonym         10
oio:hasRelatedSynonym       843
oio:id                      541
oio:inSubset                182
owl:deprecated              133
owl:disjointWith              5
owl:equivalentClass         664
rdf:type                    544
rdfs:comment                 48
rdfs:label                  826
rdfs:seeAlso                 50
rdfs:subClassOf            1379
skos:closeMatch             293
skos:exactMatch             696
skos:narrowMatch              1

In [6]:
df_d=pd.concat([raw, raw2, raw2]).drop_duplicates(keep=False)
df_d

,?term,?property,?value,?p,?v
4,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.geneontology.org/formats/oboInOwl#...,"vitamin E, familial isolated deficiency OF",<http://www.geneontology.org/formats/oboInOwl#...,OMIM:277460
5,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.geneontology.org/formats/oboInOwl#...,"vitamin E, familial isolated deficiency OF",<http://www.geneontology.org/formats/oboInOwl#...,MONDO:Lexical
7,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.geneontology.org/formats/oboInOwl#...,"ataxia, Friedreich-like, with selective vitami...",<http://www.geneontology.org/formats/oboInOwl#...,OMIM:277460
8,<http://purl.obolibrary.org/obo/MONDO_0010188>,<http://www.geneontology.org/formats/oboInOwl#...,"vitamin E, familial isolated deficiency OF; VED",<http://www.geneontology.org/formats/oboInOwl#...,OMIM:277460
395,<http://purl.obolibrary.org/obo/MONDO_0025404>,<http://www.geneontology.org/formats/oboInOwl#...,coronaviral enteritis of turkeys,<http://www.geneontology.org/formats/oboInOwl#...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4...
...,...,...,...,...,...
642137,<http://purl.obolibrary.org/obo/MONDO_0032882>,<http://www.geneontology.org/formats/oboInOwl#...,HEYN-SPROUL-JACKSON SYNDROME; HESJAS,<http://www.geneontology.org/formats/oboInOwl#...,OMIM:618724
642138,<http://purl.obolibrary.org/obo/MONDO_0032882>,<http://www.geneontology.org/formats/oboInOwl#...,OMIM:618724,<http://www.geneontology.org/formats/oboInOwl#...,MONDO:equivalentTo
642139,<http://purl.obolibrary.org/obo/MONDO_0032882>,<http://www.w3.org/2000/01/rdf-schema#subClassOf>,<http://purl.obolibrary.org/obo/MONDO_0003847>,<http://www.geneontology.org/formats/oboInOwl#...,OMIM:618724
642140,<http://purl.obolibrary.org/obo/MONDO_0032882>,<http://www.w3.org/2002/07/owl#equivalentClass>,<http://purl.obolibrary.org/obo/OMIM_618724>,None,None
642141,<http://purl.obolibrary.org/obo/MONDO_0032882>,<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>,<http://www.w3.org/2002/07/owl#Class>,None,None

In [7]:
df_xref=df_d[((df_d['?property']=="<http://www.geneontology.org/formats/oboInOwl#hasDbXref>") & (df_d['?p']!="None") & (df_d['?v']=="MONDO:equivalentTo"))].copy()
df_xref['source'] = df_xref['?value'].str.split(r":", expand=True)[0]
df_xref=df_xref[['?term','source']].drop_duplicates()
df_xref

                                                 ?term    source
1951    <http://purl.obolibrary.org/obo/MONDO_0032883>      OMIM
3394    <http://purl.obolibrary.org/obo/MONDO_0033853>  Orphanet
3960    <http://purl.obolibrary.org/obo/MONDO_0032884>      OMIM
5722    <http://purl.obolibrary.org/obo/MONDO_0032885>      OMIM
6228    <http://purl.obolibrary.org/obo/MONDO_0003036>       EFO
...                                                ...       ...
639967  <http://purl.obolibrary.org/obo/MONDO_0016825>      GARD
639971  <http://purl.obolibrary.org/obo/MONDO_0016825>      MESH
639986  <http://purl.obolibrary.org/obo/MONDO_0016825>      OMIM
640055  <http://purl.obolibrary.org/obo/MONDO_0032881>      OMIM
642138  <http://purl.obolibrary.org/obo/MONDO_0032882>      OMIM

[877 rows x 2 columns]

In [8]:
df_xref.groupby(['source']).agg(['count'])

         ?term
         count
source
COHD         5
DC           4
DOID        45
EFO         13
GARD        33
ICD10        3
ICD11        1
ICD9         8
MESH        30
NCIT        19
OMIM       437
OMIMPS      52
ONCOTREE     1
Orphanet   149
SCTID       33
UMLS        44

In [63]:
import pandas as pd
import os
report_last_release="../ontology/reports/mondo_base_last_release-report.tsv"
report_current_release="../ontology/reports/mondo_base_current_release-report.tsv"
output="../ontology/reports/release-report-changed-terms.tsv"
output_new="../ontology/reports/release-report-new-terms.tsv"

In [64]:
def load_report_data(fn, prefix):
    df = pd.read_csv(fn, sep='\t')
    df.columns = ['mondo_id', 'label', 'definition','obsoletion_candidate','obsolete']
    df['mondo_id']=[i.replace("<http://purl.obolibrary.org/obo/MONDO_","MONDO:").replace(">","") for i in df['mondo_id']]
    df_m = pd.melt(df, id_vars='mondo_id', value_vars=['label', 'definition','obsoletion_candidate','obsolete'])
    df_m.columns = ['mondo_id', 'property',	'value_'+prefix]
    return df_m

def format_new_table(df):
    if 'definition' not in df:
        df['definition'] = ''
    if 'label' not in df:
        df['label'] = ''
    if 'obsolete' not in df:
        df['obsolete'] = ''
    if 'obsoletion_candidate' not in df:
        df['obsoletion_candidate'] = ''
    df.fillna('', inplace=True)
    return df[['mondo_id','label','definition','obsolete','obsoletion_candidate']]

df_report_last_release=load_report_data(report_last_release,'old')
df_report_current_release=load_report_data(report_current_release,'new')

last_ids = df_report_last_release['mondo_id'].unique()
current_ids = df_report_current_release['mondo_id'].unique()
new_terms = [x for x in current_ids if x not in last_ids]

df_report_full= pd.merge(df_report_last_release, df_report_current_release, on=['mondo_id','property'],how='right')
df_report_full.fillna('', inplace=True)
df_report = df_report_full[df_report_full['value_old']!=df_report_full['value_new']].copy()

df_report_new=df_report[df_report['mondo_id'].isin(new_terms)].copy()
del df_report_new['value_old']
df_report_new_wide=df_report_new.pivot(index='mondo_id', columns='property', values='value_new')
df_report_new_wide=pd.DataFrame(df_report_new_wide.to_records())


df_report_new_wide = format_new_table(df_report_new_wide)
df_report_new = df_report_new_wide.copy()


df_report_changed=df_report[~df_report['mondo_id'].isin(new_terms)].copy()

df_report_new.to_csv(output_new, sep="\t",index=False)
df_report_changed.to_csv(output, sep="\t",index=False)

In [65]:
df_report_new.head()

,mondo_id,label,definition,obsolete,obsoletion_candidate
0,MONDO:0023655,"immunodeficiency 14b, autosomal recessive",,,
1,MONDO:0023657,"intellectual developmental disorder, autosomal...",,,
2,MONDO:0023659,developmental and epileptic encephalopathy 96,,,
3,MONDO:0023660,"angioedema, hereditary, 6",,,
4,MONDO:0023662,lymphatic malformation 10,,,

In [66]:
df_report_changed.head(15)

,mondo_id,property,value_old,value_new
1620,MONDO:0023603,label,hereditary connective tissue disorder,hereditary disorder of connective tissue
9164,MONDO:0007665,label,primary open angle glaucoma,"glaucoma 1, open angle, E"
9171,MONDO:0019313,label,hereditary lymphedema,lymphatic malformation
9466,MONDO:0007883,label,lazy leukocyte syndrome,"periodic fever, immunodeficiency, and thromboc..."
9510,MONDO:0007919,label,"lymphedema, hereditary, 1A",lymphatic malformation 1
9511,MONDO:0007920,label,Meige disease,lymphatic malformation 5
9572,MONDO:0007964,label,dysplastic nevus syndrome,"melanoma, cutaneous malignant, susceptibility ..."
9930,MONDO:0008233,label,phaeochromocytoma,pheochromocytoma
12352,MONDO:0010118,label,Threoninemia,inherited threoninemia
12421,MONDO:0010177,label,retinal ischemic syndrome-digestive tract smal...,vascular hyalinosis
12584,MONDO:0010301,label,"thrombocythemia, X-linked","obsolete thrombocythemia, X-linked"
13698,MONDO:0011293,label,Homocysteinemia,obsolete Homocysteinemia
14801,MONDO:0012317,label,"visceral neuropathy, familial, autosomal dominant","visceral neuropathy, familial, 3, autosomal do..."
15291,MONDO:0012765,label,"lymphedema, hereditary, 1B",lymphatic malformation 2
15367,MONDO:0012842,label,CMM7,"melanoma, cutaneous malignant, susceptibility ..."